param(
    [string]$OutDir = "kvserver win-x64",
    [switch]$Zip
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot

$out    = Join-Path (Join-Path $root "builds") $OutDir
$tmpApi = Join-Path $root "_build_api"
$tmpCli = Join-Path $root "_build_cli"

# --- Clean ---
foreach ($dir in @($out, $tmpApi, $tmpCli)) {
    if (Test-Path $dir) { Remove-Item $dir -Recurse -Force }
}
New-Item -ItemType Directory $out | Out-Null

# --- Publish API ---
Write-Host "Publishing KVServer.Api..."
dotnet publish "$root\KVServer.Api" `
    -c Release -r win-x64 `
    -p:SelfContained=false `
    -p:PublishSingleFile=true `
    -p:DebugType=none `
    -p:DebugSymbols=false `
    -o $tmpApi
if ($LASTEXITCODE -ne 0) { throw "API publish failed" }

# --- Publish CLI ---
Write-Host "Publishing KVServer.Cli..."
dotnet publish "$root\KVServer.Cli" `
    -c Release -r win-x64 `
    -p:SelfContained=false `
    -p:PublishSingleFile=true `
    -p:DebugType=none `
    -p:DebugSymbols=false `
    -o $tmpCli
if ($LASTEXITCODE -ne 0) { throw "CLI publish failed" }

# --- Collect output ---

# Binaries (rename to kvserver.exe / kvserver-cli.exe)
Copy-Item "$tmpApi\KVServer.Api.exe"  "$out\kvserver.exe"
Copy-Item "$tmpCli\KVServer.Cli.exe"  "$out\kvserver-cli.exe"

# Native libs (.dll files — e_sqlite3.dll etc.)
Get-ChildItem $tmpApi -Filter "*.dll" | ForEach-Object {
    Copy-Item $_.FullName "$out\$($_.Name)"
}

# wwwroot (with compressed .br/.gz files generated by publish)
Copy-Item "$tmpApi\wwwroot" "$out\wwwroot" -Recurse

# appsettings.json — source file only (no Development variant)
Copy-Item "$root\KVServer.Api\appsettings.json" "$out\appsettings.json"

# --- Cleanup temp dirs ---
Remove-Item $tmpApi -Recurse -Force
Remove-Item $tmpCli -Recurse -Force

# --- Optional zip ---
if ($Zip) {
    $zipPath = Join-Path $root "publish.zip"
    if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
    Compress-Archive -Path "$out\*" -DestinationPath $zipPath
    Write-Host "Archive: $zipPath"
}

Write-Host "Done: $out"
